### ISSUE TITLE
Drag out of Chart

### ISSUE THREAD

**Issue by lvarciat** [highcharts/draggable-legend#3]
options.x and options.y are computed even if you drag out of chart, so you can lose legend if you start new drag.
I suggest to compute options.x and options.y only if we are inside the chart :
//options.x = optionsX + draggedX;
//options.y = optionsY + draggedY;
if (currentX + draggedX > 0 && ...

```
                    options.x = optionsX + draggedX;
                     options.y = optionsY + draggedY;
```

**Comment by tjhiggins** [comment]
bump
