### ISSUE TITLE
draggable legend checkboxes not working

### ISSUE THREAD

**Issue by Izothep** [highcharts/draggable-legend#6]
The checkboxes are not working with draggable legend. You can move legend but checkboxes are still at the same place.

example:
http://jsfiddle.net/izothep/Le4Vc/66/

**Comment by orgalinq** [comment]
Hi,
Seems to be simple, at least for me: Leave the checkboxes.
Therefore remove: 
plotOptions: {
      series: {
        showCheckbox: true
      }
    },

Kind Regards,
Jan Walhof
