### ISSUE TITLE
installation fails due to typo in URL I guess

### ISSUE THREAD

**Issue by Phazzer** [highcharts/draggable-legend#7]
It fails when I try to install with npm:

$ npm i highcharts-draggable-legend
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/Highcharts - Not found

I guess simply Highcharts should be highcharts in the URL.

**Comment by KacperMadej** [comment]
Hi @Phazzer 

Thank you for finding the bug and reporting about it here.

**Comment by sebastianbochan** [comment]
@bre1470 @jon-a-nygaard

**Comment by bre1470** [comment]
The naming is wrong. Replace the first dash with as slash: `npm i highcharts/draggable-legend`
